Stop processing if one of the registrations matches a user account and requires login
eventespresso/eea-wpuser-integration pull request #48
Opened 2022-08-24 14:36 UTC by Pebblo

To reproduce this, require the personal information question group for additional registrants on an event.

Select at least 2 tickets.

For the primary registrant, use registration details (email) which match a user account (the admin account for example)

For the additional registrant, use any details as long as they DO NOT match a user account on the site.

With master, an empty notice will be shown in place of the log notice... because the first registration matched a user account which 'triggered' the notice, then the second registration is processed and wipes out the notice again.

This change breaks out of registration processing when a user email match is found so that the notice is shown for that specific registration.

2022-08-24 17:12 UTC, tn3rb requested changes

2022-08-24 17:12 UTC, tn3rb commented on EED_WP_Users_SPCO.module.php
> +            }
i don't think this is the best solution. 
It may work for this particular testing scenario but I'm pretty certain it will cause issues in others.

I've opened up all of the code and looked at how things are running, and it is clear that the loop below will overwrite the notices as you have described, but short circuiting the method early like you have done will not prevent that from happening in other scenarios because the value of `$stop_processing` that is passed into this function is hardcoded as `false`.

Anyways, a better solution is to simply break out of the loop below as soon as we set `$stop_processing` to true, which will prevent the notices from overwriting.

```php 
// around line 530 in the original code
if ($user_notice !== '') {
    $user_notice         .= EED_WP_Users_SPCO::loginAndRegisterButtonsHtml(
        new Url($checkout->current_step->reg_step_url())
    );
    $stop_processing     = true;
    $field_input_error[] = 'ee_reg_qstn-' . $registration->ID() . '-email';
	break; // <<<--- ADD THIS
}
```

can you plz try this solution and verify that it also fixes the issue you have reported?

2022-08-24 18:39 UTC, Pebblo commented on EED_WP_Users_SPCO.module.php
> +            }
I tried that originally, but it only breaks out of the foreach of the form_inputs on line [HERE](https://github.com/eventespresso/eea-wpuser-integration/blob/da7c19d78134fbfd986a871b3530a97572f1e951/EED_WP_Users_SPCO.module.php#L508)

What other issues do you think this might cause? I ask because the sole purpose of this specific function it to check if the email address used in the reg form is linked to a user account and if so builds a notice. As it stands the add-on (and afaict SPCO) can only handle that on a single field.

>but short circuiting the method early like you have done will not prevent that from happening in other scenarios because the value of $stop_processing that is passed into this function is hardcoded as false.

I'm counting on that fact because the loop needs to run at least once and the loop sets it to be true if one of the reg data emails matches an account. We only need to match one single instance for it to display a notice. If say Attendee 1 uses an email which matches an account and we show a login notice for that form we don't need to show an additional notice as both of them can't log in anyway.

If we show the notice and the user logs in and then changes the form data so that attende 2 now uses an email which DOES match and account, again the add-on shows the notice for them to log in (we don't allow registrations for a user account that already exists unless they log in or filter the function to turn the check off).

2022-08-24 18:54 UTC, tn3rb commented on EED_WP_Users_SPCO.module.php
> +            }
DOH! right... there's two loops there 🤦🏻 

then change my suggestion to `break 2;` so that it exists both loops

2022-08-24 20:08 UTC, Pebblo commented on EED_WP_Users_SPCO.module.php
> +            }
Haaaaa I completely forgot you could do that with break! Been a while aye.

2022-08-24 20:20 UTC, tn3rb commented on EED_WP_Users_SPCO.module.php
> +            }
is that working as you would expect now?

2022-08-24 21:12 UTC, hoseinrafiei approved these changes
### 👍

2022-08-25 02:37 UTC, tn3rb approved these changes

2022-10-03 19:46 UTC, merged